# Generated by Django 5.0.6 on 2024-06-26 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_half', models.CharField(max_length=255)),
                ('lower_half', models.CharField(max_length=255)),
                ('footwear', models.CharField(default='Shoes', max_length=255)),
                ('specs', models.CharField(default='Sun Glasses', max_length=255)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snippets.person')),
            ],
        ),
    ]
